name: Build

on:
  - push
  - workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Build
        run: go build -o fireball ./cmd

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: "npm"
          cache-dependency-path: "vscode/package-lock.json"

      - name: Install VSCE
        run: npm install -g @vscode/vsce

      - name: Package VS Code extension
        run: |
          cd vscode
          npm install
          vsce package

      - name: Upload build artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          path: |
            fireball
            vscode/*.vsix